// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__aCYvoBaVR6HFOvTIs_EvWHuipECt9k',
    appId: '1:401389738688:web:d5e170e3165aed9b0b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    authDomain: 'login-55f41.firebaseapp.com',
    storageBucket: 'login-55f41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc363sHm0IC9k3qOh_rw9ZhTScxX_tvms',
    appId: '1:401389738688:android:6341aab566c9d1390b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_k7A8FhBPKFdTisA1NTbbb8OGFkBL-A',
    appId: '1:401389738688:ios:714a6d062cc7a6e40b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
    iosClientId: '401389738688-tao1cs6qcsvaoretm0f14mkoiqsvlqqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_k7A8FhBPKFdTisA1NTbbb8OGFkBL-A',
    appId: '1:401389738688:ios:c313f3acd6db32710b2b25',
    messagingSenderId: '401389738688',
    projectId: 'login-55f41',
    storageBucket: 'login-55f41.appspot.com',
    iosClientId: '401389738688-iuit9mab5bjecieegj52v4hhrqistuc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectflutter.RunnerTests',
  );
}
